import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homepage">Homepage</Link>
        </li>
        <li>
          <Link to="/homepageboxlayout">HomepageBoxLayout</Link>
        </li>
        <li>
          <Link to="/homepage1">Homepage1</Link>
        </li>
        <li>
          <Link to="/homepage2">Homepage2</Link>
        </li>
        <li>
          <Link to="/homepage3">Homepage3</Link>
        </li>
        <li>
          <Link to="/bannar">Bannar</Link>
        </li>
        <li>
          <Link to="/shoponeone">ShopOneOne</Link>
        </li>
        <li>
          <Link to="/shoptwo">ShopTwo</Link>
        </li>
        <li>
          <Link to="/productsdetailsdescription">
            ProductsDetailsDescription
          </Link>
        </li>
        <li>
          <Link to="/productsdetailsadditionalinfoone">
            ProductsDetailsAdditionalInfoOne
          </Link>
        </li>
        <li>
          <Link to="/productdetailcustomerfeedbackone">
            ProductDetailCustomerFeedbackOne
          </Link>
        </li>
        <li>
          <Link to="/wishlistone">WishlistOne</Link>
        </li>
        <li>
          <Link to="/shoppingcartone">ShoppingCartOne</Link>
        </li>
        <li>
          <Link to="/checkoutone">CheckoutOne</Link>
        </li>
        <li>
          <Link to="/bloglist">BlogList</Link>
        </li>
        <li>
          <Link to="/singleblog">SingleBlog</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/signinone">SignInOne</Link>
        </li>
        <li>
          <Link to="/createaccountone">CreateAccountOne</Link>
        </li>
        <li>
          <Link to="/userdashboardone">UserDashboardOne</Link>
        </li>
        <li>
          <Link to="/orderhistoryone">OrderHistoryOne</Link>
        </li>
        <li>
          <Link to="/orderdetails">OrderDetails</Link>
        </li>
        <li>
          <Link to="/settingsone">SettingsOne</Link>
        </li>
        <li>
          <Link to="/faqs">FAQs</Link>
        </li>
        <li>
          <Link to="/errorpageone">ErrorPageOne</Link>
        </li>
        <li>
          <Link to="/homepageone">HomepageOne</Link>
        </li>
        <li>
          <Link to="/shopone">ShopOne</Link>
        </li>
        <li>
          <Link to="/aboutone">AboutOne</Link>
        </li>
        <li>
          <Link to="/contactone">ContactOne</Link>
        </li>
        <li>
          <Link to="/productsdetailsdescriptionone">
            ProductsDetailsDescriptionOne
          </Link>
        </li>
        <li>
          <Link to="/productsdetailsadditionalinfo">
            ProductsDetailsAdditionalInfo
          </Link>
        </li>
        <li>
          <Link to="/productdetailcustomerfeedback">
            ProductDetailCustomerFeedback
          </Link>
        </li>
        <li>
          <Link to="/wishlist">Wishlist</Link>
        </li>
        <li>
          <Link to="/shoppingcart">ShoppingCart</Link>
        </li>
        <li>
          <Link to="/checkout">Checkout</Link>
        </li>
        <li>
          <Link to="/hotdeals">HotDeals</Link>
        </li>
        <li>
          <Link to="/bannarone">BannarOne</Link>
        </li>
        <li>
          <Link to="/popularproducts">PopularProducts</Link>
        </li>
        <li>
          <Link to="/featuredproducts">FeaturedProducts</Link>
        </li>
        <li>
          <Link to="/signin">SignIn</Link>
        </li>
        <li>
          <Link to="/createaccount">CreateAccount</Link>
        </li>
        <li>
          <Link to="/userdashboard">UserDashboard</Link>
        </li>
        <li>
          <Link to="/orderhistory">OrderHistory</Link>
        </li>
        <li>
          <Link to="/orderdetailsone">OrderDetailsOne</Link>
        </li>
        <li>
          <Link to="/settings">Settings</Link>
        </li>
        <li>
          <Link to="/faqsone">FAQsOne</Link>
        </li>
        <li>
          <Link to="/errorpage">ErrorPage</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
